# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.0'

gem 'sinatra', '~> 4.0'
gem 'puma', '~> 6.0'
gem 'rackup', '~> 2.0'
gem 'json', '~> 2.7'

group :development do
  gem 'rerun', '~> 0.14'
end
